//Talia Yehuda ID: 316471978
// contains assembly code implementations for user-space system calls.Here we can define new SYSCALLs, SYSCALLCPS178 sets %eax register to be 178 which is sys_cps178.


#include "syscall.h"
#include "traps.h"

// All "standard" SYSCALLS are added by this:
#define SYSCALL(name) \
  .globl name; \
  name: \
    movl $SYS_ ## name, %eax; \
    int $T_SYSCALL; \
    ret

// !!!! Adding "new" "SYSCALLfork(fork)" instead of SYSCALL(fork) 
//  without changing syscall.h !!! 1 is SYSCALL number, look in syscall.c
#define SYSCALLFORK(name) \
  .globl name; \
  name: \
    movl $1, %eax; \
    int $T_SYSCALL; \
    ret

// You need to add your new SYSCALL by the same way(here is a good place)
#define SYSCALLCPS178(name) \
  .globl name; \
  name: \
    movl $178, %eax; \
    int $T_SYSCALL; \
    ret

SYSCALLCPS178(cps178)
SYSCALLFORK(fork) //instead of SYSCALL(fork) !!!
//SYSCALL(fork)
SYSCALL(exit)
SYSCALL(wait)
SYSCALL(pipe)
SYSCALL(read)
SYSCALL(write)
SYSCALL(close)
SYSCALL(kill)
SYSCALL(exec)
SYSCALL(open)
SYSCALL(mknod)
SYSCALL(unlink)
SYSCALL(fstat)
SYSCALL(link)
SYSCALL(mkdir)
SYSCALL(chdir)
SYSCALL(dup)
SYSCALL(getpid)
SYSCALL(sbrk)
SYSCALL(sleep)
SYSCALL(uptime)
